'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Kaarten.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property cl1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cl9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cl9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property di9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("di9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dij() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dij", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dik() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dik", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property he9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("he9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hej() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hej", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sp9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
